version: '3.8'
services:

  scalasftp:
    image: scalasftp:<localBuild>

  sftpserver:
    image: atmoz/sftp
    ports:
      - "2222:22"
    volumes:
      - ../sftp_files:/home/foo/upload
    command: foo:pass:1001
